id = "bgfx-shaderc"
name = "BGFX ShaderC"
version = "0.0.1"
schema_version = 1
authors = ["Mathias Berntsen"]
description = "Extension for parsing BGFX ShaderC shader files"
repository = "https://github.com/LawyerMorty97/bgfx-shaderc-zed-extension"
snippets = ["./snippets/bgfx shaderc.json"]

[grammars.glsl]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-glsl"
rev = "b0df9f9959665b7a17861d3ad26a786a9eb89fe1"
